driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY'] %>
  security_group_ids:  <%= ENV['AWS_SECURITY_GROUPS'] %>
  region: <%= ENV['AWS_REGION'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  require_chef_omnibus: true
  subnet_id: <%= ENV['AWS_SUBNET'] %>
  instance_type: t2.small
  associate_public_ip: false
  interface: private
  user_data: <%= ENV['USER_DATA_PATH'] %>
  tags:
    OWNER: <%= ENV['AWS_OWNER_TAG'] %>

provisioner:
  name: chef_zero

transport:
  username: cloud-user
  ssh_key: ~/.ssh/<%= ENV['AWS_SSH_KEY'] %>.pem

platforms:
  - name: <%= ENV['AWS_PLATFORM_NAME'] %>
    driver:
      image_id: <%= ENV['AWS_AMI_ID'] %>

suites:
  - name: default
    run_list:
#      - recipe[gd-test-helper]
      - recipe[snap-a-matic-15000]
